version: '3.8'
services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PATH=/venv/bin:$PATH
      - PYTHONPATH=/app
    ports:
      - "8014:8014"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8014/users/"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5